# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Hugo Phantom"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE.md"
description = "Ported theme of HTML5 UP."
homepage = "http://siteforthistheme.com/"
tags = ["blog", "responsive"]
features = ["", ""]
min_version = 0.15

[author]
  name = "Jan Ulrich Hasecke"
  homepage = "http://www.hasecke.com"

# If porting an existing theme
[original]
  name = "Phantom"
  homepage = "https://html5up.net/phantom"
  repo = ""
